### PR TITLE
Update copyright years

### PR DESCRIPTION
**Pull request by logankilpatrick**

### CODE REVIEW

**Review by bkamins — APPROVED** [review]

**Comment by bkamins** [comment]
@nalimilan - OK to merge?

**Comment by nalimilan** [comment]
Why not. Though I'm not sure it makes sense to update this every year. AFAIK this doesn't have any legal value.

**Comment by logankilpatrick** [comment]
Not really for legal value, just when I see sites with a really old year, I assume no one maintains or uses them anymore so more so a charade to make the content still seem relevant

**Comment by ViralBShah** [comment]
Yeah no legal value - it just makes it appear unmaintained.

**Pull request merged**
